src/stripepy/cli/download.py
src/stripepy/cli/setup.py
src/stripepy/main.py

StripePy download is a new subcommand that aims to simplify downloading datasets that can be used to test StripePy.
Example usage:
```bash
stripepy download --list-only
stripepy download
stripepy download --max-size 512
stripepy download -o my_precious.hic
stripepy download --name 4DNFIOTPSS3L
stripepy download --refrence-genome dm6
```

Implement stripepy download

---

src/stripepy/stripepy.py
src/stripepy/utils/postprocessing.py
src/stripepy/utils/stripe.py

Refactor the Stripe class with the following aims:
- Improve error checking
- Mark all fields as private and expose properties and stats using read-only attributes
- Split computation into smaller functions
- Add documentation
- Make unit testing more straight forward

Refactor Stripe class

---

src/stripepy/utils/stripe.py

These attributes are needed when stripepy call is given the `--roi` param.

Stripe class: expose seed and topological persistence as attributes

---

src/stripepy/cli/setup.py

Given an output folder like `a/b/c`, this check is supposed to ensure that folder `a/b/` exists.
If this is the case, then it should return path `a/b/c`.
While refactoring, this was incorrectly changed such that the last component is always dropped.
This PR restores the old behavior.

Fix validation logic in _output_dir_checked()

---

src/stripepy/cli/call.py
src/stripepy/cli/setup.py
src/stripepy/stripepy.py
src/stripepy/utils/finders.py

- Add new `--nproc` flag to control the maximum level of parallelism used by `stripepy call`
- Reuse process pools as much as possible

Add --nproc to stripepy call

---

.dockerignore
Dockerfile
utils/devel/build_dockerfile.sh

Add Dockerfile for StripePy.
The Dockerfile requires several `--build-arg` in order to build properly.
Script `utils/devel/build_dockerfile.sh` takes care of automatically infer all required build arguments and build a docker image targeting the native architecture.
Example usage:
```bash
utils/devel/build_dockerfile.sh
utils/devel/build_dockerfile.sh linux/amd64,linux/arm4
```

Add Dockerfile

---

src/stripepy/cli/call.py
src/stripepy/stripepy.py

This PR implements the following changes to the attributes stored in the HDF5 generated by `stripepy call`:
The layout generated by `stripepy call` from this PR corresponds to v1 of the HDF5 schema.

Restructure output HDF5 file layout

---

.github/workflows/ci.yml
src/stripepy/cli/call.py
src/stripepy/cli/setup.py
src/stripepy/main_over_MoDLE.py
src/stripepy/stripepy.py
utils/devel/test_docker_image.sh

The flag glob-pers-type has been removed, as it was always used with its default option "constant".
This change partially addresses #58

Remove flag glob-pers-type

---

.github/workflows/build-dockerfile.yml
.github/workflows/ci.yml
src/stripepy/cli/download.py
utils/devel/test_docker_image.sh

Update the tests datasets known to `stripepy download` and used by the CI with the datasets from [10.5281/zenodo.14283921](https://doi.org/10.5281/zenodo.14283921).
This was done with the following aims:
- Use more realistic datasets (e.g. mammalian Hi-C files instead of very sparse drosophila files)
- Reduce file size by not storing interactions that will never be used by StripePy (e.g. trans interactions and interactions very far away from the matrix diagonal)
- Have more control on the test datasets by hosting them ourselves.
We downloaded the datasets from the 4DNucleome Data portal and ENCODE.
Datasets were processed as follows:
- Convert all datasets to .mcool format using `hictk convert`
- Fix .mcool files downloaded from the 4DNucleome using `hictk fix-mcool`
- Minify the .mcool …

Update the test datasets

---

src/stripepy/cli/setup.py

We set as default parameters those values used for real Hi-C contact maps at a resolution of 10 kb (H1-hESC and GM12878).

Set default parameters

---

pyproject.toml
src/stripepy/IO.py
src/stripepy/__init__.py
src/stripepy/cli/setup.py

The stripepy namespace is not available on PyPI.
There is no actual package with this name, but I suspect the package name has been parked by Stripe Inc. to avoid name confusion when installing their Python API: https://github.com/stripe/stripe-python
Beside the package name, nothing has changed: the entrypoint for the CLI is still called `stripepy` and all library code resides under the `stripepy` namespace.

Rename package from stripepy to stripepy-hic

---

src/stripepy/cli/setup.py

Closes https://github.com/paulsengroup/StripePy/issues/78.

Improve error messages issued upon failure of CLI argument type validation

---

.github/workflows/ci.yml
Dockerfile
README.md
pyproject.toml
src/stripepy/cli/call.py
src/stripepy/cli/download.py
src/stripepy/cli/plot.py
src/stripepy/cli/view.py
src/stripepy/main.py
src/stripepy/plot.py
src/stripepy/stripepy.py
src/stripepy/utils/common.py
src/stripepy/utils/progress_bar.py
test/integration/__init__.py
test/integration/common.py
test/integration/test_stripepy_call.py
test/integration/test_stripepy_plot.py

Drop `seaborn` and `scikit-learn`, as they are no longer needed.
StripePy recently picked up several dependencies that are nice-to-have, but that are not strictly needed to call stripes using `stripepy call`.
These dependencies have been made optional, such that users are not prevented from installing StripePy in case there are problems with one of these dependencies.
matplotlib is used throughout the codebase to generate plots.
However, `stripepy call` and `stripepy view` do not require matplotlib (or at least this is the case when `stripepy call` is run without specifying `--roi=*`).
Thus, I restructured import statements such that we import matplotlib only when strictly needed.
When running code that requires `matplotlib` and we are unable to import the module, an error like the …

[dependencies] remove unused dependency and reduce number of core dependencies

---

src/stripepy/stripepy.py

".2g" is replaced with ".f" so that plots are listed in the correct canonical ordering, i.e., with increasing thresholding of the relative change parameter.

Correct bug in file name inside _plot_stripes_helper

---

src/stripepy/cli/download.py
src/stripepy/cli/view.py
src/stripepy/plot.py
src/stripepy/stripepy.py
src/stripepy/utils/TDA.py
src/stripepy/utils/common.py
src/stripepy/utils/persistence1d.py
test/integration/common.py
test/integration/test_stripepy_call.py
test/integration/test_stripepy_download.py

Fix two bugs that resulted in different results being returned when running stripepy call on different platform (and potentially even when using different versions of numpy and pandas).
The first bug was caused by not forcing numpy and pandas to use stable sorting algorithms.
The second bug was due to minor difference in FP arithmetic on different architectures.
This first bug resulted in slightly different results produced on macOS and Linux (Windows and Linux produced consistent results).
The second bug resulted in different results when using different architectures (or even different CPUs with the same arch).

[bug] Fix inconsistent results produced on different platforms

---

src/stripepy/stripepy.py
src/stripepy/utils/finders.py
src/stripepy/utils/regressions.py

On my dev machine the optimization results in a 40% improvement in single-threaded performance.
The time required to estimate stripe witdths for chr1 dropped from 3.413s to 23.947ms.
Supersedes https://github.com/paulsengroup/StripePy/pull/90.
<details>
<summary>Timings</summary>
Baseline:
```
Command being timed: "venv/bin/stripepy call test/data/4DNFI9GMP2J8.mcool 10000 -o /tmp/stripepy-devel/ --force --verbosity=debug"
User time (seconds): 116.81
System time (seconds): 1.79
Percent of CPU this job got: 103%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:55.06
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 1294200
Average resident set size (kbytes): 0
Major …
```

[performance]: optimize find_HIoIs()

---

.github/.codecov.yml
.github/workflows/build-dockerfile.yml
README.md
benchmark/run-over-StripeBench.py
src/stripepy/IO.py
src/stripepy/cli/call.py
src/stripepy/cli/download.py
src/stripepy/cli/plot.py
src/stripepy/cli/setup.py
src/stripepy/cli/view.py
src/stripepy/main.py
src/stripepy/stripepy.py
test/integration/test_stripepy_call.py
test/unit/test_IO.py
utils/devel/test_docker_image.sh

In brief:
- replace `--output-folder` with `--output-file`. When `--output-file` is not provided, create an output file named like `{{prefix}}.{{resolution}}.hdf5`, where `{{prefix}}` is the file name of the input matrix (without extension) and `{{resolution}}` is the matrix resolution
- add parameter `--plot-dir` to instruct `stripepy call` where to store the plots generated when `--roi=*` is provided
- add parameter `--log-file` to tell `stripepy call` where to store its log file. When not provided, log messages are only printed to stdout
In addition, I took this occasion to also clean up the CLI parsing logic for all subcommands.

[refactor]: restructure stripepy call outputs

---

src/stripepy/stripepy.py

We now simply check that the neighborhood size is a positive number, while further testing is moved to unit testing.

Simplify assertion for neighborhood size

---

.github/workflows/build-dockerfile.yml
.github/workflows/ci.yml
src/stripepy/cli/download.py
src/stripepy/utils/stripe.py
test/integration/test_stripepy_download.py
test/integration/test_stripepy_view.py

Fix an off by one error in the logic that slicing the genome-wide sparse matrix prior to computing a stripe biodescriptors.
As can be seen in the scatterplots, this rarely changes the biodescriptors in a significant way:
[attachements.tar.gz](https://github.com/user-attachments/files/18561878/attachements.tar.gz)

[bug]: fix off-by-one error in code computing stripe biodescriptors

---

src/stripepy/plot.py
src/stripepy/stripepy.py

Ensure only stripes that are fully enclosed in a given region of interest are plotted using `stripepy plot` or `stripepy call ... --roi=*`.

[bug]: correct bound checking in stripe plotting code

---

pyproject.toml
src/stripepy/algorithms/step1.py
src/stripepy/data_structures/concurrent.py

On my machine, this yields a ~25% perf improvement and a 60% reduction in peak memory usage when processing 4DNFI9GMP2J8.mcool at 10kb using 16 CPU cores (note that this applies to the genome-wide version of the .mcool, not the minified version we use for testing).
Running stripepy on the same file converted to .hic v9 using hictk convert yields an even better perf improvement of approx 40%.

[perf]: take advantage of the new hictkpy.File.fetch() capabilities

---

benchmark/run-over-StripeBench.py

This commit updates the default value of the topological persistence threshold, which was necessary after changing the way the relative change parameter is computed.

Update default topological persistence threshold
